name: Himid Daily Report
on:
  schedule:
    - cron: '0 17 * * 1-5'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build Rust Module & Run Python
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          MISTRALAI_API_KEY: ${{ secrets.MISTRALAI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run Linters
        run: |
          # 1. Lint Python Ruff
          echo "Running Python linter (Ruff)..."
          uv run ruff check .
          
          # 2. Lint Rust Clippy (himid-core folder)
          echo "Running Rust linter (Clippy)..."
          cd himid-core
          cargo clippy -- -D warnings
          cd ..

      - name: Build Rust Module & Run Python
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          MISTRALAI_API_KEY: ${{ secrets.MISTRALAI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # 1. Compile Rust module (Maturin with uv)
          cd himid-core
          uv run maturin develop --release
          
          # 2. Go to folder root and start script
          cd ..
          mkdir -p assets
          uv run python src/main.py